import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { motion } from "framer-motion";
import Swal from "sweetalert2";
import jsPDF from "jspdf";
import {
  FaDownload,
  FaMoneyBillWave,
  FaRoute,
  FaTimesCircle,
} from "react-icons/fa";

import axiosInstance from "../../../api/axiosInstance";
import LoadingSpinner from "../../../components/ui/LoadingSpinner";

const formatDateTime = (dateValue) => {
  if (!dateValue) return "Not set";

  return new Date(dateValue).toLocaleString("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  });
};

const statusClassMap = {
  pending: "status-pending",
  accepted: "status-accepted",
  rejected: "status-rejected",
  cancelled: "status-cancelled",
  paid: "status-paid",
};

const MyBookings = () => {
  const queryClient = useQueryClient();

  const {
    data: bookings = [],
    isLoading,
    isError,
  } = useQuery({
    queryKey: ["myBookings"],
    queryFn: async () => {
      const response = await axiosInstance.get("/api/bookings/my-bookings");
      return response.data.bookings || [];
    },
  });

  const cancelMutation = useMutation({
    mutationFn: async (bookingId) => {
      const response = await axiosInstance.patch(
        `/api/bookings/${bookingId}/cancel`
      );
      return response.data;
    },
    onSuccess: () => {
      Swal.fire({
        icon: "success",
        title: "Booking Cancelled",
        timer: 1400,
        showConfirmButton: false,
      });

      queryClient.invalidateQueries({ queryKey: ["myBookings"] });
    },
    onError: (error) => {
      Swal.fire(
        "Cancel Failed",
        error.response?.data?.message || "Something went wrong.",
        "error"
      );
    },
  });

  const paymentMutation = useMutation({
    mutationFn: async (bookingId) => {
      try {
        await axiosInstance.post("/api/payments/create-payment-intent", {
          bookingId,
        });
      } catch (error) {
        if (!error.response?.data?.fallbackAvailable) {
          throw error;
        }
      }

      const response = await axiosInstance.post("/api/payments/mock-success", {
        bookingId,
      });

      return response.data;
    },
    onSuccess: () => {
      Swal.fire({
        icon: "success",
        title: "Payment Successful",
        text: "Your booking is now paid.",
        timer: 1600,
        showConfirmButton: false,
      });

      queryClient.invalidateQueries({ queryKey: ["myBookings"] });
      queryClient.invalidateQueries({ queryKey: ["myTransactions"] });
    },
    onError: (error) => {
      Swal.fire(
        "Payment Failed",
        error.response?.data?.message || "Something went wrong.",
        "error"
      );
    },
  });

  const handleCancelBooking = async (bookingId) => {
    const result = await Swal.fire({
      title: "Cancel this booking?",
      text: "You can cancel only before vendor accepts it.",
      icon: "warning",
      showCancelButton: true,
      confirmButtonText: "Yes, cancel",
      cancelButtonText: "No",
    });

    if (result.isConfirmed) {
      cancelMutation.mutate(bookingId);
    }
  };

  const handlePayNow = async (bookingId) => {
    const result = await Swal.fire({
      title: "Confirm Payment?",
      text: "This will complete payment using development demo payment if Stripe key is not configured.",
      icon: "question",
      showCancelButton: true,
      confirmButtonText: "Pay Now",
      cancelButtonText: "Cancel",
    });

    if (result.isConfirmed) {
      paymentMutation.mutate(bookingId);
    }
  };

  const downloadTicketPDF = (booking) => {
    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.text("TicketBari E-Ticket", 20, 22);

    doc.setFontSize(12);
    doc.text(`Ticket: ${booking.ticketTitle}`, 20, 40);
    doc.text(`Route: ${booking.from} to ${booking.to}`, 20, 50);
    doc.text(`Transport: ${booking.transportType}`, 20, 60);
    doc.text(`Passenger: ${booking.userName}`, 20, 70);
    doc.text(`Email: ${booking.userEmail}`, 20, 80);
    doc.text(`Quantity: ${booking.bookingQuantity}`, 20, 90);
    doc.text(
      `Seats: ${
        booking.selectedSeats?.length ? booking.selectedSeats.join(", ") : "N/A"
      }`,
      20,
      100
    );
    doc.text(`Total Paid: $${booking.totalPrice}`, 20, 110);
    doc.text(`Transaction ID: ${booking.transactionId || "N/A"}`, 20, 120);
    doc.text(`Departure: ${formatDateTime(booking.departureDateTime)}`, 20, 130);
    doc.text(`Status: ${booking.status}`, 20, 140);

    doc.setFontSize(10);
    doc.text("Generated by TicketBari Online Ticket Booking Platform", 20, 160);

    doc.save(`TicketBari-${booking._id}.pdf`);
  };

  if (isLoading) {
    return <LoadingSpinner message="Loading your bookings..." />;
  }

  if (isError) {
    return (
      <section className="dashboard-panel">
        <h1>My Bookings</h1>
        <div className="empty-state">Failed to load bookings.</div>
      </section>
    );
  }

  return (
    <motion.section
      className="dashboard-panel"
      initial={{ opacity: 0, y: 18 }}
      animate={{ opacity: 1, y: 0 }}
    >
      <div className="dashboard-page-head">
        <div>
          <span className="dashboard-kicker">User Dashboard</span>
          <h1>My Booked Tickets</h1>
          <p className="muted-text">
            Track booking requests, payments, cancellation, and download paid
            e-tickets.
          </p>
        </div>
      </div>

      {bookings.length === 0 ? (
        <div className="empty-state">You have no booking yet.</div>
      ) : (
        <div className="booking-card-list">
          {bookings.map((booking) => (
            <motion.article
              className="booking-card"
              key={booking._id}
              whileHover={{ y: -5 }}
            >
              <div className="booking-card-main">
                <div className="booking-icon">
                  <FaRoute />
                </div>

                <div>
                  <h3>{booking.ticketTitle}</h3>
                  <p>
                    {booking.from} → {booking.to}
                  </p>
                  <small>{formatDateTime(booking.departureDateTime)}</small>
                </div>
              </div>

              <div className="booking-info-grid">
                <div>
                  <span>Transport</span>
                  <strong>{booking.transportType}</strong>
                </div>

                <div>
                  <span>Quantity</span>
                  <strong>{booking.bookingQuantity}</strong>
                </div>

                <div>
                  <span>Seats</span>
                  <strong>
                    {booking.selectedSeats?.length
                      ? booking.selectedSeats.join(", ")
                      : "N/A"}
                  </strong>
                </div>

                <div>
                  <span>Total</span>
                  <strong>${booking.totalPrice}</strong>
                </div>
              </div>

              <div className="booking-action-row">
                <span
                  className={`booking-status ${
                    statusClassMap[booking.status] || ""
                  }`}
                >
                  {booking.status}
                </span>

                <div className="booking-actions">
                  {booking.status === "pending" && (
                    <button
                      type="button"
                      className="danger-action-btn"
                      onClick={() => handleCancelBooking(booking._id)}
                      disabled={cancelMutation.isPending}
                    >
                      <FaTimesCircle />
                      Cancel
                    </button>
                  )}

                  {booking.status === "accepted" && (
                    <button
                      type="button"
                      className="pay-action-btn"
                      onClick={() => handlePayNow(booking._id)}
                      disabled={paymentMutation.isPending}
                    >
                      <FaMoneyBillWave />
                      Pay Now
                    </button>
                  )}

                  {booking.status === "paid" && (
                    <button
                      type="button"
                      className="download-action-btn"
                      onClick={() => downloadTicketPDF(booking)}
                    >
                      <FaDownload />
                      Download PDF
                    </button>
                  )}
                </div>
              </div>
            </motion.article>
          ))}
        </div>
      )}
    </motion.section>
  );
};

export default MyBookings;